@startuml
title ページ遷移図
bbs : 掲示板
del_post:GET 削除確認\nPOST 削除
posting:GET 投稿確認\nPOST 投稿

[*]->bbs
bbs-->del_post:リンク\ntid
del_post-->del_post:POST\n tid
del_post-->bbs:リンク
bbs-->posting:リンク
posting-->posting:POST
posting-->bbs:リンク
@enduml